Create initial calcAllMoves function and unit test
Note that this function fails the following test with:
BackgammonTests > canCalculateAllMoves() FAILED
    org.opentest4j.AssertionFailedError: Should return only valid legal moves to be played. ==> expected: <[[4-0,3-0], [4-1,3-0]]> but was: <[[25-21], [23-19], [22-18]]>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1152)
        at app//backgammon.BackgammonTests.canCalculateAllMoves(BackgammonTests.java:77)